BEGIN;

CREATE TABLE IF NOT EXISTS metrics (
			id VARCHAR(128) NOT NULL PRIMARY KEY,
			mType VARCHAR(128) NOT NULL,
			value DOUBLE PRECISION DEFAULT NULL,
			delta BIGINT DEFAULT NULL
		);

COMMIT;